import { Course, LibraryDocument, User, Role, ChatMessage } from '../types';

export const mockCourses: Course[] = [
  {
    id: '1',
    code: 'CA-101',
    name: 'Introducción a las Ciencias Ambientales',
    teacher: 'Dr. Carlos Morales (Docente)',
    credits: 4,
    schedule: 'L-M-V 10-11am',
    enrolled: true,
    capacity: 50,
    enrolledCount: 45,
    prerequisites: [],
  },
  {
    id: '2',
    code: 'BIO-205',
    name: 'Ecología de Ecosistemas',
    teacher: 'Dra. Rios',
    credits: 4,
    schedule: 'M-J 2-4pm',
    enrolled: false,
    capacity: 40,
    enrolledCount: 38,
    prerequisites: ['CA-101'],
  },
  {
    id: '3',
    code: 'GEO-310',
    name: 'Sistemas de Información Geográfica (SIG)',
    teacher: 'Ing. Vega',
    credits: 3,
    schedule: 'L-M 4-5:30pm',
    enrolled: true,
    capacity: 30,
    enrolledCount: 25,
    prerequisites: ['CA-101'],
  },
  {
    id: '4',
    code: 'QUIM-220',
    name: 'Química Ambiental',
    teacher: 'Dr. Soto',
    credits: 4,
    schedule: 'M-J 8-10am',
    enrolled: false,
    capacity: 40,
    enrolledCount: 40,
    prerequisites: ['QUIM-101'],
  },
  {
    id: '5',
    code: 'LEG-401',
    name: 'Legislación Ambiental',
    teacher: 'Lic. Peña',
    credits: 3,
    schedule: 'V 4-7pm',
    enrolled: false,
    capacity: 60,
    enrolledCount: 55,
    prerequisites: [],
  },
];

export const mockDocuments: LibraryDocument[] = [
  {
    id: '1',
    title: 'Principios de Sostenibilidad',
    author: 'John Doe',
    category: 'Sostenibilidad',
    publishDate: '2022-05-15',
    url: '#',
  },
  {
    id: '2',
    title: 'Manual de Cartografía Digital',
    author: 'Jane Smith',
    category: 'Cartografía',
    publishDate: '2021-11-20',
    url: '#',
  },
  {
    id: '3',
    title: 'Tratamiento de Aguas Residuales',
    author: 'Peter Jones',
    category: 'Recursos Hídricos',
    publishDate: '2023-01-30',
    url: '#',
  },
  {
    id: '4',
    title: 'Impacto Ambiental: Guía Práctica',
    author: 'Emily White',
    category: 'Evaluación de Impacto',
    publishDate: '2022-08-10',
    url: '#',
  },
];

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Ana García',
    email: 'ana.garcia@email.com',
    role: Role.ESTUDIANTE,
    avatarUrl: 'https://picsum.photos/seed/anagarcia/100/100',
  },
  {
    id: '2',
    name: 'Dr. Carlos Morales',
    email: 'carlos.morales@email.com',
    role: Role.DOCENTE,
    avatarUrl: 'https://picsum.photos/seed/carlosmorales/100/100',
  },
  {
    id: '3',
    name: 'Laura Martinez',
    email: 'laura.martinez@email.com',
    role: Role.ADMINISTRATIVO,
    avatarUrl: 'https://picsum.photos/seed/lauramartinez/100/100',
  },
  {
    id: '4',
    name: 'Director Ricardo Solis',
    email: 'ricardo.solis@email.com',
    role: Role.DIRECTIVO,
    avatarUrl: 'https://picsum.photos/seed/ricardosolis/100/100',
  },
  {
    id: '5',
    name: 'Laura Rojas',
    email: 'laura.rojas@email.com',
    role: Role.BIBLIOTECARIO,
    avatarUrl: 'https://picsum.photos/seed/laurarojas/100/100',
  },
];

export const mockChatMessages: ChatMessage[] = [
  {
    id: 1,
    userId: '2',
    userName: 'Dr. Carlos Morales',
    avatarUrl: 'https://picsum.photos/seed/carlosmorales/100/100',
    text: 'Recuerden que la entrega del proyecto de CA-101 es el próximo viernes.',
    timestamp: '10:30 AM',
  },
  {
    id: 2,
    userId: '1',
    userName: 'Ana García',
    avatarUrl: 'https://picsum.photos/seed/anagarcia/100/100',
    text: 'Entendido, gracias por el recordatorio, Dr. Morales.',
    timestamp: '10:31 AM',
  },
  {
    id: 3,
    userId: '5',
    userName: 'Pedro Ramirez',
    avatarUrl: 'https://picsum.photos/seed/pedroramirez/100/100',
    text: '¿Podríamos tener una sesión de preguntas y respuestas antes de la entrega?',
    timestamp: '10:32 AM',
  },
  {
    id: 4,
    userId: '2',
    userName: 'Dr. Carlos Morales',
    avatarUrl: 'https://picsum.photos/seed/carlosmorales/100/100',
    text: 'Claro, podemos hacer una el miércoles en la hora de clase.',
    timestamp: '10:35 AM',
  },
];
